from src.server.adapters import (
    ArtifactReferenceAdapter,
    EngineLaunchAdapter,
    EngineStatusProjectionAdapter,
    ExecutionRecordResultAdapter,
    TraceEventAdapter,
    ValidationFindingAdapter,
)
from src.server.auth_adapter import (
    AuthorizationGate,
    ClerkAuthAdapter,
    RequestAuthResolver,
    build_engine_auth_context_refs,
    describe_request_auth_context,
)
from src.server.auth_models import (
    AuthenticatedIdentity,
    AuthorizationDecision,
    AuthorizationInput,
    RequestAuthContext,
    RunAuthorizationContext,
    SessionContext,
    WorkspaceAuthorizationContext,
)
from src.server.database_foundation import (
    build_postgres_connection_url,
    build_server_schema_summary,
    get_server_schema_families,
    load_postgres_connection_settings_from_env,
)
from src.server.database_models import (
    ColumnSpec,
    IndexSpec,
    MigrationScript,
    MigrationStep,
    PostgresConnectionSettings,
    SchemaFamily,
    TableSpec,
)
from src.server.run_admission import ExecutionTargetResolver, RunAdmissionService
from src.server.run_admission_models import (
    ExecutionTargetCatalogEntry,
    ProductAdmissionPolicy,
    ProductClientContext,
    ProductExecutionTarget,
    ProductLaunchOptions,
    ProductRunLaunchAcceptedResponse,
    ProductRunLaunchLinks,
    ProductRunLaunchRejectedResponse,
    ProductRunLaunchRequest,
    ResolvedExecutionTarget,
    RunAdmissionOutcome,
    RunRecordProjection,
)
from src.server.worker_queue_models import (
    QueueJobProjection,
    QueueSubmission,
    WorkerClaim,
    WorkerLeasePolicy,
    WorkerOrphanReview,
    WorkerProjectionBundle,
)
from src.server.worker_queue_orchestration import WorkerQueueOrchestrationService
from src.server.run_read_api import RunResultReadService, RunStatusReadService
from src.server.run_list_api import RunListReadService
from src.server.artifact_trace_read_api import ArtifactReadService, TraceReadService
from src.server.workspace_onboarding_api import OnboardingContinuityService, WorkspaceRegistryService
from src.server.http_route_models import HttpRouteRequest, HttpRouteResponse
from src.server.http_route_surface import RunHttpRouteSurface
from src.server.framework_binding_models import (
    FrameworkInboundRequest,
    FrameworkOutboundResponse,
    FrameworkRouteDefinition,
)
from src.server.framework_binding import FrameworkRouteBindings
try:
    from src.server.fastapi_binding_models import FastApiBindingConfig, FastApiRouteDependencies
    from src.server.fastapi_binding import FastApiRouteBindings, create_fastapi_app
    _FASTAPI_BINDING_AVAILABLE = True
except ModuleNotFoundError as exc:
    if exc.name != "fastapi":
        raise
    _FASTAPI_BINDING_AVAILABLE = False

from src.server.workspace_onboarding_models import (
    OnboardingReadOutcome,
    OnboardingWriteOutcome,
    ProductOnboardingLinks,
    ProductOnboardingReadResponse,
    ProductOnboardingRejectedResponse,
    ProductOnboardingStateView,
    ProductOnboardingWriteAcceptedResponse,
    ProductOnboardingWriteRequest,
    ProductWorkspaceCreateRequest,
    ProductWorkspaceDetailResponse,
    ProductWorkspaceLinks,
    ProductWorkspaceListResponse,
    ProductWorkspaceReadRejectedResponse,
    ProductWorkspaceSummaryView,
    ProductWorkspaceWriteAcceptedResponse,
    ProductWorkspaceWriteRejectedResponse,
    WorkspaceListOutcome,
    WorkspaceReadOutcome,
    WorkspaceWriteOutcome,
)
from src.server.run_list_models import (
    ProductRunListAppliedFilters,
    ProductRunListItemView,
    ProductRunListLinks,
    ProductRunListRejectedResponse,
    ProductWorkspaceRunListResponse,
    RunListReadOutcome,
)
from src.server.run_read_models import (
    ProductArtifactRefView,
    ProductEngineSignalView,
    ProductExecutionTargetView,
    ProductFinalOutputView,
    ProductResultSummaryView,
    ProductRunLinks,
    ProductRunProgressView,
    ProductRunReadRejectedResponse,
    ProductRunResultResponse,
    ProductRunStatusResponse,
    ProductTraceRefView,
    RunResultReadOutcome,
    RunStatusReadOutcome,
)
from src.server.artifact_trace_read_models import (
    ArtifactDetailReadOutcome,
    ArtifactListReadOutcome,
    ProductArtifactDetailResponse,
    ProductArtifactPayloadAccess,
    ProductArtifactSummary,
    ProductArtifactTraceReadRejectedResponse,
    ProductRunArtifactsResponse,
    ProductRunTraceResponse,
    ProductTraceEventView,
    ProductTraceFocusView,
    TraceReadOutcome,
)
from src.server.migration_foundation import (
    build_initial_server_migration,
    build_migration_file_text,
    render_postgres_schema_statements,
    validate_schema_families,
)
from src.server.boundary_models import (
    EngineArtifactReference,
    EngineCorrelationContext,
    EngineExecutionBinding,
    EngineExecutionTarget,
    EngineFailureInfo,
    EngineFinalOutput,
    EngineResultEnvelope,
    EngineRunLaunchRequest,
    EngineRunLaunchResponse,
    EngineRunStatusSnapshot,
    EngineRuntimeOptions,
    EngineSignal,
    EngineTraceEvent,
    EngineValidationEnvelope,
    EngineValidationFinding,
)

__all__ = [
    "ArtifactReferenceAdapter",
    "AuthenticatedIdentity",
    "AuthorizationDecision",
    "AuthorizationGate",
    "AuthorizationInput",
    "ClerkAuthAdapter",
    "EngineArtifactReference",
    "EngineCorrelationContext",
    "EngineExecutionBinding",
    "EngineExecutionTarget",
    "EngineFailureInfo",
    "EngineFinalOutput",
    "EngineLaunchAdapter",
    "EngineResultEnvelope",
    "EngineRunLaunchRequest",
    "EngineRunLaunchResponse",
    "EngineRunStatusSnapshot",
    "EngineRuntimeOptions",
    "EngineSignal",
    "EngineStatusProjectionAdapter",
    "EngineTraceEvent",
    "EngineValidationEnvelope",
    "EngineValidationFinding",
    "ExecutionRecordResultAdapter",
    "RequestAuthContext",
    "RequestAuthResolver",
    "RunAuthorizationContext",
    "SessionContext",
    "TraceEventAdapter",
    "ValidationFindingAdapter",
    "WorkspaceAuthorizationContext",
    "ExecutionTargetCatalogEntry",
    "ExecutionTargetResolver",
    "ProductAdmissionPolicy",
    "ProductClientContext",
    "ProductExecutionTarget",
    "ProductLaunchOptions",
    "ProductRunLaunchAcceptedResponse",
    "ProductRunLaunchLinks",
    "ProductRunLaunchRejectedResponse",
    "ProductRunLaunchRequest",
    "ResolvedExecutionTarget",
    "RunAdmissionOutcome",
    "RunAdmissionService",
    "RunRecordProjection",
    "QueueJobProjection",
    "QueueSubmission",
    "WorkerClaim",
    "WorkerLeasePolicy",
    "WorkerOrphanReview",
    "WorkerProjectionBundle",
    "WorkerQueueOrchestrationService",
    "WorkspaceRegistryService",
    "OnboardingContinuityService",
    "ProductWorkspaceCreateRequest",
    "ProductWorkspaceDetailResponse",
    "ProductWorkspaceLinks",
    "ProductWorkspaceListResponse",
    "ProductWorkspaceReadRejectedResponse",
    "ProductWorkspaceSummaryView",
    "ProductWorkspaceWriteAcceptedResponse",
    "ProductWorkspaceWriteRejectedResponse",
    "WorkspaceListOutcome",
    "WorkspaceReadOutcome",
    "WorkspaceWriteOutcome",
    "ProductOnboardingLinks",
    "ProductOnboardingReadResponse",
    "ProductOnboardingRejectedResponse",
    "ProductOnboardingStateView",
    "ProductOnboardingWriteAcceptedResponse",
    "ProductOnboardingWriteRequest",
    "OnboardingReadOutcome",
    "OnboardingWriteOutcome",
    "ProductRunListAppliedFilters",
    "ProductRunListItemView",
    "ProductRunListLinks",
    "ProductRunListRejectedResponse",
    "ProductWorkspaceRunListResponse",
    "RunListReadOutcome",
    "RunListReadService",
    "ProductArtifactRefView",
    "ProductEngineSignalView",
    "ProductExecutionTargetView",
    "ProductFinalOutputView",
    "ProductResultSummaryView",
    "ProductRunLinks",
    "ProductRunProgressView",
    "ProductRunReadRejectedResponse",
    "ProductRunResultResponse",
    "ProductRunStatusResponse",
    "ProductTraceRefView",
    "RunResultReadOutcome",
    "RunResultReadService",
    "RunStatusReadOutcome",
    "RunStatusReadService",
    "ArtifactDetailReadOutcome",
    "ArtifactListReadOutcome",
    "ArtifactReadService",
    "ProductArtifactDetailResponse",
    "ProductArtifactPayloadAccess",
    "ProductArtifactSummary",
    "ProductArtifactTraceReadRejectedResponse",
    "ProductRunArtifactsResponse",
    "ProductRunTraceResponse",
    "ProductTraceEventView",
    "ProductTraceFocusView",
    "TraceReadOutcome",
    "TraceReadService",
    "HttpRouteRequest",
    "HttpRouteResponse",
    "RunHttpRouteSurface",
    "FrameworkInboundRequest",
    "FrameworkOutboundResponse",
    "FrameworkRouteBindings",
    "FrameworkRouteDefinition",
    "build_engine_auth_context_refs",
    "build_initial_server_migration",
    "build_migration_file_text",
    "build_postgres_connection_url",
    "build_server_schema_summary",
    "ColumnSpec",
    "describe_request_auth_context",
    "get_server_schema_families",
    "IndexSpec",
    "load_postgres_connection_settings_from_env",
    "MigrationScript",
    "MigrationStep",
    "PostgresConnectionSettings",
    "render_postgres_schema_statements",
    "SchemaFamily",
    "TableSpec",
    "validate_schema_families",
]

if _FASTAPI_BINDING_AVAILABLE:
    __all__.extend([
        "FastApiBindingConfig",
        "FastApiRouteBindings",
        "FastApiRouteDependencies",
        "create_fastapi_app",
    ])
