# Spec ↔ Code Version Sync Constants
# This module belongs to the contracts layer (not runtime logic).

ENGINE_EXECUTION_MODEL_VERSION = "1.6.0"
ENGINE_TRACE_MODEL_VERSION = "1.4.0"
VALIDATION_ENGINE_CONTRACT_VERSION = "1.2.0"
VALIDATION_RULE_CATALOG_VERSION = "1.1.0"
VALIDATION_RULE_LIFECYCLE_VERSION = "1.0.0"
EXECUTION_ENVIRONMENT_CONTRACT_VERSION = "1.4.0"
