from __future__ import annotations

STRUCTURE_OUTPUT_TYPE_MISMATCH = "STRUCTURE_OUTPUT_TYPE_MISMATCH"
STRUCTURE_REQUIRED_KEY_MISSING = "STRUCTURE_REQUIRED_KEY_MISSING"
REQUIREMENT_EMPTY_OUTPUT = "REQUIREMENT_EMPTY_OUTPUT"
REQUIREMENT_TEXT_TOO_SHORT = "REQUIREMENT_TEXT_TOO_SHORT"
REQUIREMENT_REQUIRED_TEXT_MISSING = "REQUIREMENT_REQUIRED_TEXT_MISSING"
LOGIC_FORBIDDEN_TEXT_PRESENT = "LOGIC_FORBIDDEN_TEXT_PRESENT"
LOGIC_FIELD_EQUALITY_VIOLATION = "LOGIC_FIELD_EQUALITY_VIOLATION"
UNKNOWN_VERIFIER_EXCEPTION = "UNKNOWN_VERIFIER_EXCEPTION"

VERIFIER_REASON_CODES = {
    STRUCTURE_OUTPUT_TYPE_MISMATCH,
    STRUCTURE_REQUIRED_KEY_MISSING,
    REQUIREMENT_EMPTY_OUTPUT,
    REQUIREMENT_TEXT_TOO_SHORT,
    REQUIREMENT_REQUIRED_TEXT_MISSING,
    LOGIC_FORBIDDEN_TEXT_PRESENT,
    LOGIC_FIELD_EQUALITY_VIOLATION,
    UNKNOWN_VERIFIER_EXCEPTION,
}

VERIFIER_REGRESSION_SEVERITY_HIGH = "HIGH"
VERIFIER_REGRESSION_SEVERITY_MEDIUM = "MEDIUM"
VERIFIER_REGRESSION_SEVERITY_LOW = "LOW"

VERIFIER_REASON_CODE_TO_REGRESSION_SEVERITY = {
    STRUCTURE_OUTPUT_TYPE_MISMATCH: VERIFIER_REGRESSION_SEVERITY_HIGH,
    STRUCTURE_REQUIRED_KEY_MISSING: VERIFIER_REGRESSION_SEVERITY_HIGH,
    REQUIREMENT_EMPTY_OUTPUT: VERIFIER_REGRESSION_SEVERITY_HIGH,
    REQUIREMENT_REQUIRED_TEXT_MISSING: VERIFIER_REGRESSION_SEVERITY_HIGH,
    LOGIC_FORBIDDEN_TEXT_PRESENT: VERIFIER_REGRESSION_SEVERITY_HIGH,
    UNKNOWN_VERIFIER_EXCEPTION: VERIFIER_REGRESSION_SEVERITY_HIGH,
    LOGIC_FIELD_EQUALITY_VIOLATION: VERIFIER_REGRESSION_SEVERITY_MEDIUM,
    REQUIREMENT_TEXT_TOO_SHORT: VERIFIER_REGRESSION_SEVERITY_LOW,
}

_VERIFIER_REGRESSION_SEVERITY_ORDER = {
    VERIFIER_REGRESSION_SEVERITY_LOW: 0,
    VERIFIER_REGRESSION_SEVERITY_MEDIUM: 1,
    VERIFIER_REGRESSION_SEVERITY_HIGH: 2,
}


def get_verifier_regression_severity(reason_codes: list[str] | tuple[str, ...] | set[str] | frozenset[str]) -> str | None:
    mapped = [
        VERIFIER_REASON_CODE_TO_REGRESSION_SEVERITY[code]
        for code in reason_codes
        if code in VERIFIER_REASON_CODE_TO_REGRESSION_SEVERITY
    ]
    if not mapped:
        return None
    return max(mapped, key=_VERIFIER_REGRESSION_SEVERITY_ORDER.__getitem__)
