from __future__ import annotations

STRUCTURE_OUTPUT_TYPE_MISMATCH = "STRUCTURE_OUTPUT_TYPE_MISMATCH"
STRUCTURE_REQUIRED_KEY_MISSING = "STRUCTURE_REQUIRED_KEY_MISSING"
REQUIREMENT_EMPTY_OUTPUT = "REQUIREMENT_EMPTY_OUTPUT"
REQUIREMENT_TEXT_TOO_SHORT = "REQUIREMENT_TEXT_TOO_SHORT"
REQUIREMENT_REQUIRED_TEXT_MISSING = "REQUIREMENT_REQUIRED_TEXT_MISSING"
LOGIC_FORBIDDEN_TEXT_PRESENT = "LOGIC_FORBIDDEN_TEXT_PRESENT"
LOGIC_FIELD_EQUALITY_VIOLATION = "LOGIC_FIELD_EQUALITY_VIOLATION"
UNKNOWN_VERIFIER_EXCEPTION = "UNKNOWN_VERIFIER_EXCEPTION"

VERIFIER_REASON_CODES = {
    STRUCTURE_OUTPUT_TYPE_MISMATCH,
    STRUCTURE_REQUIRED_KEY_MISSING,
    REQUIREMENT_EMPTY_OUTPUT,
    REQUIREMENT_TEXT_TOO_SHORT,
    REQUIREMENT_REQUIRED_TEXT_MISSING,
    LOGIC_FORBIDDEN_TEXT_PRESENT,
    LOGIC_FIELD_EQUALITY_VIOLATION,
    UNKNOWN_VERIFIER_EXCEPTION,
}
